{{ define "header" }}
{{- $inject := inject -}}
{{- if first -}}
# Package {{ pkg }} contains generated code for schema '{{ schema }}'.
{{ end -}}

# Code generated by xo. DO NOT EDIT.

import datetime
from typing import Optional, TYPE_CHECKING
from {{ pkg }}.db import *
{{ range imports }}
import {{ .Pkg }}{{ with .Alias }} as {{ . }} {{ end }}
{{ end }}

if TYPE_CHECKING:
    pass

{{- if $inject }}
{{ $inject }}
{{- end }}
{{ end }}
