{{ define "header" }}
{{- $inject := inject -}}
{{- if first -}}
# Package {{ pkg }} contains generated code for schema '{{ schema }}'.
{{ end -}}

# Code generated by xo. DO NOT EDIT.

import datetime
from typing import Optional
from {{ pkg }}.db import *
{{ range imports }}
import {{ .Pkg }}{{ with .Alias }} as {{ . }} {{ end }}
{{ end }}

{{- if $inject }}
{{ $inject }}
{{- end }}
{{ end }}
